# Generated by Django 5.0.6 on 2024-10-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('session', models.CharField(choices=[('openmat', 'Open Mat'), ('sparring', 'Sparring'), ('positionalsparring', 'Positional Sparring'), ('drills', 'Drills')], default='drills', max_length=32)),
            ],
        ),
    ]
